### ISSUE TITLE
Crash on joining world (reported by Vienhackar)

### ISSUE THREAD

**Issue by pkmnfrk** [pkmnfrk/equivalentintegrations#38]
```
java.lang.NullPointerException: Unexpected error
	at com.mike_caron.equivalentintegrations.storage.EMCItemHandler.<init>(EMCItemHandler.java:65)
	at com.mike_caron.equivalentintegrations.integrations.bbw.TabletContainerHandler.countItems(TabletContainerHandler.java:33)
	at portablejim.bbw.containers.ContainerManager.countItems(ContainerManager.java:55)
	at portablejim.bbw.shims.BasicPlayerShim.countItems(BasicPlayerShim.java:69)
	at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:81)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:53)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3224_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by pkmnfrk** [comment]
This is actually a duplicate of #31
